#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=<experiment-name>
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# activate the environment
source activate camus

root=/scratch/$USER
mkdir -p $root

code_dir= $HOME/CBIM-Medical-Image-Segmentation/

python training_pipeline.py

